<?php
class RecordOrm extends AppOrm{
	public $id = '';
	public $name = '';
	public $cardNo = '';
	public $descriot = '';
	public $ctfTp = '';
	public $ctfId = '';
	public $gender = '';
	public $birthday = '';
	public $address = '';
	public $zip = '';
	public $dirty = '';
	public $district1 = '';
	public $district2 = '';
	public $district3 = '';
	public $district4 = '';
	public $district5 = '';
	public $district6 = '';
	public $firstNm = '';
	public $lastNm = '';
	public $duty = '';
	public $mobile = '';
	public $tel = '';
	public $fax = '';
	public $email = '';
	public $nation = '';
	public $taste = '';
	public $education = '';
	public $company = '';
	public $ctel = '';
	public $caddress = '';
	public $czip = '';
	public $family = '';
	public $version = '';
	public $exten_id = '';
}
