<?php
class ConstComponent extends Component{
	static public $cards = array(
			array('numberClass' => 'two', 'flowerClass' => 'spades', 'value' => 2),
			array('numberClass' => 'two', 'flowerClass' => 'hearts', 'value' => 2),
			array('numberClass' => 'two', 'flowerClass' => 'clubs', 'value' => 2),
			array('numberClass' => 'two', 'flowerClass' => 'diamonds', 'value' => 2),
			array('numberClass' => 'three', 'flowerClass' => 'spades', 'value' => 3),
			array('numberClass' => 'three', 'flowerClass' => 'hearts', 'value' => 3),
			array('numberClass' => 'three', 'flowerClass' => 'clubs', 'value' => 3),
			array('numberClass' => 'three', 'flowerClass' => 'diamonds', 'value' => 3),
			array('numberClass' => 'four', 'flowerClass' => 'spades', 'value' => 4),
			array('numberClass' => 'four', 'flowerClass' => 'hearts', 'value' => 4),
			array('numberClass' => 'four', 'flowerClass' => 'clubs', 'value' => 4),
			array('numberClass' => 'four', 'flowerClass' => 'diamonds', 'value' => 4),
			array('numberClass' => 'five', 'flowerClass' => 'spades', 'value' => 5),
			array('numberClass' => 'five', 'flowerClass' => 'hearts', 'value' => 5),
			array('numberClass' => 'five', 'flowerClass' => 'clubs', 'value' => 5),
			array('numberClass' => 'five', 'flowerClass' => 'diamonds', 'value' => 5),
			array('numberClass' => 'six', 'flowerClass' => 'spades', 'value' => 6),
			array('numberClass' => 'six', 'flowerClass' => 'hearts', 'value' => 6),
			array('numberClass' => 'six', 'flowerClass' => 'clubs', 'value' => 6),
			array('numberClass' => 'six', 'flowerClass' => 'diamonds', 'value' => 6),
			array('numberClass' => 'seven', 'flowerClass' => 'spades', 'value' => 7),
			array('numberClass' => 'seven', 'flowerClass' => 'hearts', 'value' => 7),
			array('numberClass' => 'seven', 'flowerClass' => 'clubs', 'value' => 7),
			array('numberClass' => 'seven', 'flowerClass' => 'diamonds', 'value' => 7),
			array('numberClass' => 'eight', 'flowerClass' => 'spades', 'value' => 8),
			array('numberClass' => 'eight', 'flowerClass' => 'hearts', 'value' => 8),
			array('numberClass' => 'eight', 'flowerClass' => 'clubs', 'value' => 8),
			array('numberClass' => 'eight', 'flowerClass' => 'diamonds', 'value' => 8),
			array('numberClass' => 'nine', 'flowerClass' => 'spades', 'value' => 9),
			array('numberClass' => 'nine', 'flowerClass' => 'hearts', 'value' => 9),
			array('numberClass' => 'nine', 'flowerClass' => 'clubs', 'value' => 9),
			array('numberClass' => 'nine', 'flowerClass' => 'diamonds', 'value' => 9),
			array('numberClass' => 'ten', 'flowerClass' => 'spades', 'value' => 10),
			array('numberClass' => 'ten', 'flowerClass' => 'hearts', 'value' => 10),
			array('numberClass' => 'ten', 'flowerClass' => 'clubs', 'value' => 10),
			array('numberClass' => 'ten', 'flowerClass' => 'diamonds', 'value' => 10),
			array('numberClass' => 'jack', 'flowerClass' => 'spades', 'value' => 11),
			array('numberClass' => 'jack', 'flowerClass' => 'hearts', 'value' => 11),
			array('numberClass' => 'jack', 'flowerClass' => 'clubs', 'value' => 11),
			array('numberClass' => 'jack', 'flowerClass' => 'diamonds', 'value' => 11),
			array('numberClass' => 'dame', 'flowerClass' => 'spades', 'value' => 12),
			array('numberClass' => 'dame', 'flowerClass' => 'hearts', 'value' => 12),
			array('numberClass' => 'dame', 'flowerClass' => 'clubs', 'value' => 12),
			array('numberClass' => 'dame', 'flowerClass' => 'diamonds', 'value' => 12),
			array('numberClass' => 'king', 'flowerClass' => 'spades', 'value' => 13),
			array('numberClass' => 'king', 'flowerClass' => 'hearts', 'value' => 13),
			array('numberClass' => 'king', 'flowerClass' => 'clubs', 'value' => 13),
			array('numberClass' => 'king', 'flowerClass' => 'diamonds', 'value' => 13),
			array('numberClass' => 'ace', 'flowerClass' => 'spades', 'value' => 14),
			array('numberClass' => 'ace', 'flowerClass' => 'hearts', 'value' => 14),
			array('numberClass' => 'ace', 'flowerClass' => 'clubs', 'value' => 14),
			array('numberClass' => 'ace', 'flowerClass' => 'diamonds', 'value' => 14),
			array('numberClass' => 'joker', 'flowerClass' => 'joker_small', 'value' => 15),
			array('numberClass' => 'joker', 'flowerClass' => 'joker_big', 'value' => 16)
	);
}
?>